# <center> Numpy_study1 </center>

## Numpy의 기본 사용법

## Numpy란?

- Numpy는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구.
- 현실 세계의 다양한 데이터는 배열 형태로 표현할 수 있음.
- Python의 기본 List에 비해 빠르고 강력한 기능을 제공. 
- 선형대수와 관련된 다양한 기능 제공.
- 반복문 없이 데이터 배열에 대한 처리를 지원.


## Numpy의 차원
- 1차원 축(행): axis 0 => Vector
- 2차원 축(열): axis 1 => Matrix(행렬)
- 3차원 축(채널): axis 2 => Tensor(3차원 이상) 

## List를 Numpy로 바꾸어 보기

In [6]:
import numpy as np

list_data = [1, 2, 3]
array = np.array(list_data)


print(array.size) # 배열의 크기 (리스트에서는 제공 X)
print(array.dtype) # 배열 원소의 타입 (리스트에서는 제공 X)
print(array[2])   # 인덱스 2의 원소

3
int32
3


## Numpy 배열 초기화 하기

In [43]:
# 실제 데이터 분석과 관련한 다양한 처리를 할 때
# 랜덤한 데이터를 여러 개 만들거나, 행렬 곱을 하는 등 다양한 기본적 연산을 제공하는 기능이 필요함.
# 이것들을 Numpy가 제공!

# 0부터 3까지 배열 만들기
array1 = np.arange(4)
print(array1)


    
print('----------------------------------------------------------------')

# 특정한 데이터를 만들되 각 데이터가 0으로 초기화 시키고 싶을 때
array2 = np.zeros((4,4)) 
# 4*4 크기의 하나의 2차원 배열을 만들고, 모든 값들이 0으로 초기화 되도록 해줌.
print(array2)



print('----------------------------------------------------------------')

# 1로 초기화 시키고 싶을 때
array3 = np.ones((3,3), dtype = str) # dtype을 str으로 받는 것도 가능
print(array3)

print('----------------------------------------------------------------')

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기 (많이 사용!!)
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

print('----------------------------------------------------------------')

# 또한 Numpy로 통계적으로 특정한 분포를 따르는 데이터 생성 가능
# 평균이 0이고, 표준편차가 1인 표준 정규 분포를 따르는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)


[0 1 2 3]
----------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------------------------------------------------------
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
----------------------------------------------------------------
[[6 4 2]
 [8 9 0]
 [9 9 5]]
----------------------------------------------------------------
[[ 0.08652543 -2.35560241 -0.32752235]
 [ 2.66535733 -0.00532567 -1.13339079]
 [ 1.98494489 -0.99043233  1.29487562]]


## Numpy 배열 형태 바꾸기

In [28]:
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2,2))

print(array2.shape)

(2, 2)


## Numpy 배열 합치기

In [48]:
# 가로 축으로 합치기
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array3 = np.concatenate([array1, array2]) 

print(array3.shape) # 크기 (6개의 데이터가 담겨있는 배열)
print(array3)

print('----------------------------------------------------')

# 세로 축으로 합치기
array4 = np.arange(4).reshape(1,4)
array5 = np.arange(8).reshape(2,4)


array6 = np.concatenate([array4, array5], axis = 0)

print(array6.shape)
print(array6)

(6,)
[1 2 3 4 5 6]
----------------------------------------------------
(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


## Numpy 배열 나누기

In [55]:
array = np.arange(8).reshape(2, 4)

left, right = np.split(array, [2], axis = 1)

print(left)
print(right)
print(right[1][1])

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
7
