# <center> Numpy 기초연습문제 </center>

In [1]:
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3, 4))  # 3행 4열의 zero matrix
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a.shape[0]

3

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [4]:
for i in range(a.shape[0]):      # 행
    for j in range(a.shape[1]):  # 열 
        a[i, j] = i*4 + j + 1    # 아래와 같이 값이 나올 수 있도록 계산
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [5]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num          # a[0, 0] = 1, a[0, 1] = 2, a[0, 2] = 3... num에 계속 +1
        num += 1 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [6]:
a[1, 2] # 2행 3열

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [7]:
a.shape   # 3X4 shape을 가짐

(3, 4)

In [8]:
a[[1], :]   # 2번째 행 전부 출력 

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [9]:
a[:,[1, 2]]   # 행 = all, 열 = 두번째, 세번째 열만

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [10]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6]) 
# boolean indexing을 사용해 6보다 작거나 같은 값들만 추출
result

array([1., 2., 3., 4., 5., 6.])

In [11]:
a[a <= 6]   

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [12]:
b = np.random.random((3, 4))   # random.ranodm을통해 0 - 1사이의 무작위로 생성된 3행 4열 ndarry생성
b

array([[0.71117608, 0.06847561, 0.30427492, 0.46631721],
       [0.17627363, 0.60549917, 0.80861471, 0.67555816],
       [0.24806925, 0.63497463, 0.64686808, 0.62284351]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [13]:
c = a * b   
c

array([[0.71117608, 0.13695122, 0.91282477, 1.86526884],
       [0.88136817, 3.63299505, 5.660303  , 5.40446532],
       [2.23262321, 6.34974629, 7.11554884, 7.47412218]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [14]:
d = b.T    # 전치행렬 = 행과 열을 교환  ex. 3행 4열 -> 4행 3열 
d

array([[0.71117608, 0.17627363, 0.24806925],
       [0.06847561, 0.60549917, 0.63497463],
       [0.30427492, 0.80861471, 0.64686808],
       [0.46631721, 0.67555816, 0.62284351]])

In [15]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [16]:
print(a.shape, d.shape) # 차원 크기

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오

In [17]:
e = a.dot(d)  # 행렬곱 계산
e

array([[ 3.62622092,  6.51534879,  5.94999679],
       [ 9.82719623, 15.57913154, 14.56101865],
       [16.02817154, 24.6429143 , 23.17204051]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [18]:
np.sum(e, axis=1)  # axis = 1로 열의 합 계산

array([16.09156649, 39.96734642, 63.84312635])